### ISSUE TITLE
 not authorized `copy' @ error/constitute.c

### ISSUE THREAD

**Issue by uloeber** [malonge/RaGOO#10]
Hi,
can you explain what might be the issue with the following error message:

```
$ ragoo.py contigs.fa ref.fa
from: can't read /var/mail/collections
[[Bimport-im6.q16: not authorized `copy' @ error/constitute.c/WriteImage/1037.
from: can't read /var/mail/intervaltree
from: can't read /var/mail/ragoo_utilities.PAFReader
from: can't read /var/mail/ragoo_utilities.SeqReader
from: can't read /var/mail/ragoo_utilities.ContigAlignment
from: can't read /var/mail/ragoo_utilities.ContigAlignment
from: can't read /var/mail/ragoo_utilities.ContigAlignment
from: can't read /var/mail/ragoo_utilities.GFFReader
from: can't read /var/mail/ragoo_utilities.utilities
from: can't read /var/mail/ragoo_utilities.break_chimera
/home/user/.local/bin/ragoo.py: line 16: syntax error near unexpected token `('
/home/user/.local/bin/ragoo.py: line 16: `def write_contig_clusters(unique_dict, thresh, skip_list):'

$ python -V
Python 3.6.7

```

I'm running ubuntu 18.04
installed ragoo in a python3 env

Thanks in advance!
Ulrike

**Comment by malonge** [comment]
Hi there,

Though you have installed with a virtualenv, it looks like that environment is not active. In fact, I think it is trying to run `ragoo.py` as a bash script.

Have you activated the virtual environment? Your command prompt should look more like this:

`$ (ragoo_VE) ragoo.py contigs.fa ref.fa` where "ragoo_VE" is the name of your virtualenv.

**Comment by uloeber** [comment]
/home/user/bin/miniconda2/envs/mypython3/bin/ragoo.py

**Comment by malonge** [comment]
I suppose the next thing to try is this:

`/home/user/bin/miniconda2/envs/mypython3/bin/ragoo.py contigs.fa ref.fa`

**Comment by uloeber** [comment]
using the full path prints the same error :/

**Comment by malonge** [comment]
Hmm so just to double check, even if you run with the full path, you get the following error:

```/home/user/.local/bin/ragoo.py: line 16: syntax error near unexpected token `('```

Is that right?

**Comment by uloeber** [comment]
no sorry, slightly different
```
Traceback (most recent call last):
  File "/home/user/bin/miniconda2/envs/mypython3/bin/ragoo.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.2', 'ragoo.py')
  File "/home/user/bin/miniconda2/envs/mypython3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/bin/miniconda2/envs/mypython3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/ragoo.py' not found in metadata at '/home/user/.local/lib/python3.6/site-packages/RaGOO-1.2.egg-info'
```

**Comment by malonge** [comment]
Perhaps you could try recreating your virtualenv using `--no-site-packages`. I am worried that there might be some cross-talk between your python installations.

**Comment by malonge** [comment]
I'm closing this since this appears to be a problem with your python setup. Though let me know if anything new comes up.

**Comment by uloeber** [comment]
Hi Michael,to sad. I created a new python3 env, with the result:from: can't read /var/mail/collections
import-im6.q16: not authorized `copy' @ error/constitute.c/WriteImage/1037.
from: can't read /var/mail/intervaltree
from: can't read /var/mail/ragoo_utilities.PAFReader
from: can't read /var/mail/ragoo_utilities.SeqReader
from: can't read /var/mail/ragoo_utilities.ContigAlignment
from: can't read /var/mail/ragoo_utilities.ContigAlignment
from: can't read /var/mail/ragoo_utilities.ContigAlignment
from: can't read /var/mail/ragoo_utilities.GFFReader
from: can't read /var/mail/ragoo_utilities.utilities
from: can't read /var/mail/ragoo_utilities.break_chimera
/home/user/.local/bin/ragoo.py: line 16: syntax error near unexpected token `('
/home/user/.local/bin/ragoo.py: line 16: `def write_contig_clusters(unique_dict, thresh, skip_list):'

If somebody else is coming up with that issue it would be great if you could keep me up to date.By the way, did you ever compared the performance of RaGOO with multi-CSAR?
Best wishes,Ulrike
 
   Am Mittwoch, 10. April 2019, 15:21:06 MESZ hat Michael Alonge <notifications@github.com> Folgendes geschrieben: 
 
 
I'm closing this since this appears to be a problem with your python setup. Though let me know if anything new comes up.

**Comment by malonge** [comment]
Hi there,

I will definitely keep you posted if someone else has similar problems.

And multi-CSAR is for scaffolding based on multiple reference genomes, whereas RaGOO is only for a single reference and a single set of contigs.

**Comment by malonge** [comment]
Hi There,

I think I might have figured out what went wrong. I need to add a shebang to the script files. Can you please download the latest code from github and try again?

**Comment by malonge** [comment]
Hi there - I am fairly certain this issue has been resolved, but please reopen if not.
