### ISSUE TITLE
Some general queries 

### ISSUE THREAD

**Issue by koushik1989** [malonge/RaGOO#11]
Hi, I intend to use RaGOO in my workflow to build larger scaffolds from the contigs. I have the following general questions for which I did not find answers in the manuscript.
1. The reference I have is a nanopore assembly which was De novo assembled which I need to use as a reference. I have 4 more genomes of close related organisms assembled to contigs and are through Illumina sequencing. My reference is also fragmented but has good N50 value. Is it advisable to use >1Mb sequences from my nanopore assembly as a reference and build pseudomolecules using Illumina data?

2. Will the N's present in my nanopore assembly affect the scaffolding in any manner ?

3. Should I be masking (simple and low complexity) both reference and query and proceed or can I carry out the analyses with unmasked sequences?

4. Will scaffolding be affected if a diverged organism is used as a reference?

your response will help me a lot as I am new to bioinformatics.
Thanks in advance

**Comment by malonge** [comment]
Hi there,

1. I don't quite understand the question. What do you mean by "build pseudomolecules using Illumina data" Do you mean your contigs which were built from Illumina data?

2. You should be totally fine with "N"s in the reference.

3. You do not need to mask low-complexity sequences. 

4.  Please see [here](https://github.com/malonge/RaGOO/wiki#how-closely-related-does-my-assembly-have-to-be-to-the-reference-genome) for an answer to this question.
