### ISSUE TITLE
Multiple assemblers

### ISSUE THREAD

**Issue by kokyriakidis** [malonge/RaGOO#13]
Hello, could I use multiple assemblers, concat the contigs and the use RaGOO? Are there advantages to this approach? I am talking about de novo assembly with illumina reads only

**Comment by malonge** [comment]
Hi there,

Are you saying that you would take two independent assemblies and concatenate them into one file, then use that as the reference?

**Comment by kokyriakidis** [comment]
No! Two or three independent assemblies from different assembly programs (E.g. Masurca, Abyss etc), concatenate them into one single Fasta file. This file would be the final contigs. This file will be used against the reference file.

I thought that using multiple assembler could yield more contigs from different regions because it’s assembler prefers some regions better than others.

**Comment by malonge** [comment]
I would not recommend doing this. Even though the union of all contigs _may_ contain more of the genome, there will be too much redundancy in the assembly for accurate ordering and ordering.

There are plenty of genome reconciliation tools out there that you may want to look into for this task. Perhaps [Ragout](https://github.com/fenderglass/Ragout) will suit your needs.

**Comment by kokyriakidis** [comment]
What's the difference between Ragout and RaGOO? I haven't really unterstood

**Comment by malonge** [comment]
Ragoo is designed for a single reference genome and a single assembly. Therefore, it uses a pairwise aligner (Minimap2) to inform pseudomolecule construction.

Ragout is a tool for genome reconciliation, which compares many assemblies with each other (>= 2).
