### ISSUE TITLE
Empty Chr0 record

### ISSUE THREAD

**Issue by gbdias** [malonge/RaGOO#14]
Hey Michael,

- I think right now (v1.1) RaGOO outputs the unplaced `>Chr0` sequence record even when there is no unplaced sequences.
- So far I've gotten only warnings from this empty record when passing my RaGOO scaffolds to other software, but maybe consider not including it when it's empty?
- I guess an empty >Chr0 is diagnostic that no contigs are unplaced, so perhaps it should be there... Anyway, just thought I mentioned this here since the current output may be incompatible with some post-processing tools and need editing.

Best,
Gui

**Comment by malonge** [comment]
Thank you Gui, 

You have been very helpful in catching these sorts of things. I will fix this as well as address #12 in the next version. Hopefully, that will be ready soonish. 

Mike

**Comment by malonge** [comment]
Hi there, 

This has been fixed in v1.1

d6f68368addbff63b853915c00b881a46f96d35d

Thanks for bringing it to my attention.
