### ISSUE TITLE
Feature request: keep unassigned contigs separate, rather than gluing them into 'Chr0'?

### ISSUE THREAD

**Issue by SchwarzEM** [malonge/RaGOO#15]
RaGOO looks wonderful!  But ... it assigns unmapped contigs to a pseudochromosome, Chr0.

Would it be possible to have an option to have RaGOO, instead of putting unmapped contigs into 'Chr0', keep them as unligated contig sequences?

It isn't hard to get around the Chr0 issue for DNA sequence alone (just split Chr0 on 'N' residues and voila, free contigs again!).  But hacking a lifted-over GFF is considerably harder if it lifts genes to Chr0 and one really wants free contigs instead.

**Comment by malonge** [comment]
Hi there,

Yes, I should definitely add this functionality. I will incorporate into the next version and will let you know when it is ready. Thanks for bringing it to my attention.

**Comment by SchwarzEM** [comment]
Thanks for your fast reply, and for providing this very useful program!

**Comment by malonge** [comment]
Hi there,

This feature has been added as a part of the upgrade to v1.1 here:

d6f68368addbff63b853915c00b881a46f96d35d

To write unplaced sequences individually instead of writing to chr0, please use `-C`. Please let me know if you spot any problems.

Thank you!
