### ISSUE TITLE
Data cannot be updated

### ISSUE THREAD

**Issue by FAFUyangyang** [malonge/RaGOO#16]
hello，Why do I stop here when I run ragoo and the data don't  update

[M::worker_pipeline::2085.531*2.87] mapped 165627 sequences
[M::worker_pipeline::2109.052*2.87] mapped 511234 sequences
[M::worker_pipeline::2121.037*2.87] mapped 393467 sequences
[M::main] Version: 2.15-r906-dirty
[M::main] CMD: minimap2 -k19 -w19 -t3 ../../Data/asm.fasta ../../Data/draft.asm.fasta
[M::main] Real time: 2121.506 sec; CPU: 6091.642 sec; Peak RSS: 28.659 GB

**Comment by malonge** [comment]
Hi there,

I am sorry but I don't understand your question. Can you also post your command?

**Comment by malonge** [comment]
I will close this, but please reopen if you have a response.
