### ISSUE TITLE
RaGOO failed  Mapping short reads with minimap2 -- RuntimeWarning: Mean of empty slice

### ISSUE THREAD

**Issue by bbalog87** [malonge/RaGOO#22]
Hi @malonge,

I was trying to scaffold an assembly using your great tool. However I keep getting this warning and the minimap2 mapping is not done all. 

Here is the command I ran using python3 :

 ```python ../ragoo.py -b -R PE.inter.fq -T sr -t 100 -g 250 -C ../6000flye.ctg.fa ../PFLA.genome.fasta```

And here the error-message

```
nkal/anaconda3/bin/minimap2 6000flye.ctg.fa  PFLA.genome.fasta 
Sun Jul 28 19:44:09 2019 --- Misassembly correction has been turned on. This automatically inactivates chimeric contig correction.
Sun Jul 28 19:44:09 2019 --- Reading alignments
Sun Jul 28 19:44:09 2019 --- Aligning raw reads to contigs
Sun Jul 28 19:44:09 2019 --- Computing contig coverage
/home/nguinkal/anaconda3/envs/mypython3/lib/python3.7/site-packages/numpy-1.17.0-py3.7-linux-x86_64.egg/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/nguinkal/anaconda3/envs/mypython3/lib/python3.7/site-packages/numpy-1.17.0-py3.7-linux-x86_64.egg/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

Best,
Julien

**Comment by malonge** [comment]
Hi there,

Please look at `ragoo_output/ctg_alignments/reads_against_ctg.paf`. Is that file empty? And if so, can you share the contents of `ragoo_output/ctg_alignments/reads_against_ctg.paf.log`?

Thanks

**Comment by bbalog87** [comment]
Hi Michael,

Indeed, ```ragoo_output/ctg_alignments/reads_against_ctg.paf``` is empty.
[reads_against_ctg.paf.log](https://github.com/malonge/RaGOO/files/3441000/reads_against_ctg.paf.log)
I find it strange that it complains about opening the PE.inter.fq file


Again here is the command I used:
```./ragoo.py -m /home/nguinkal/anaconda3/bin/minimap2 -b -R /disk2/nguinkal/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/QC/Corrected/Zander.hiseqxPE/PE.inter.fq -T sr -t 120 -C 6000flye.ctg.fa PFLA.genome.fasta ```

Best,
Julien

**Comment by malonge** [comment]
I see what is going on. Unfortunately, though I plan on changing this in the future, all of the files have to be in your current working directory when running RaGOO. So see if this works:

```
ln -s /disk2/nguinkal/mnt/winpro/I3-NGS-Daten/NGS-Fisch/Zander-Project_2017_2020/Analysis/QC/Corrected/Zander.hiseqxPE/PE.inter.fq
./ragoo.py -m /home/nguinkal/anaconda3/bin/minimap2 -b -R PE.inter.fq -T sr -t 120 -C 6000flye.ctg.fa PFLA.genome.fasta
```

Also, be sure to remove the `ctg_alignments` directory so that it knows that it must make a new alignment file.

**Comment by bbalog87** [comment]
Hi @malonge,
It seems to work now, since minimap2 is running for more than 1h, which has not happened before. Making a symbolic link of the PE-reads within the the same directory as ragoo.py might have fixed the issue.
Thank very much for the prompt and helpful support.
Best,
Julien

**Comment by malonge** [comment]
Thanks - yes sorry for the inconvenience. This is one of the top things on my TODO list since it is much more convenient to be able to provide a path.
