### ISSUE TITLE
Scaffolding overlapping contigs

### ISSUE THREAD

**Issue by MaestSi** [malonge/RaGOO#23]
Hi,
I would like to know what is the behaviour of RaGOO when, doing the reference-based scaffolding, it finds out that some contigs are partially overlapped. This might be the result of assemblying a highly heterozygous genome. I also have Bionano data that I could use for doing the scaffolding.
Moreover I would like to ask you for an advice: starting from Falcon-Unzip contigs my idea would be to run purge_haplotigs for removing haplotipic duplication, running RaGOO and finally correcting inconsistencies using Bionano data, similar to what was done with Hi-C data in the publication. Would you advice changing the order of the last two steps?
After the Bionano scaffolding, the genome is composed of 220 scaffolds, so it is definitely not at chromosome level (19 chrs expected in Vitis vinifera). Thanks

**Comment by malonge** [comment]
Hi there,

RaGOO does not account for potential haplotype duplication in any way. Likely, such overlapping contigs will end up getting placed right next to each other in the final pseudomolecules. If one believes these duplications may exist in their assembly, I encourage them to use tools like purge_haplotigs prior to using RaGOO.

To better answer your second question, may I ask what species you are assembling? It really depends on the quality of the reference genome. It also depends on how divergent your assembly is from the reference.

**Comment by MaestSi** [comment]
You mean running `purge_haplotigs clip`, right? I am assemblying a Vitis vinifera genome. The reference genome is Pinot Noir PN40024, and it is at chromosome level. I can't say how much they are divergent: it is a different cultivar from the same species.

**Comment by malonge** [comment]
I have never used purge_haplotigs myself, but any method to remove haplotype redundancy will do.

I do not have experience with that particular species, but generally speaking, different cultivars of the same species tend to have shared chromosomal structure. By the way, I also should have asked how contiguous your assembly is, but I will assume it is decent if it is a falcon assembly.

In a perfect world, I would suggest both pipelines (Bionano then RaGOO and just RaGOO) and compare the assemblies. You can also use your error-corrected long reads from Falcon to break potential misassemblies, either introduced by Falcon or Bionano. That might be a good compromise.

**Comment by malonge** [comment]
I'll close this for now but let me know if you have any more questions or updates.

Thanks!

**Comment by MaestSi** [comment]
Ok, thanks!
