### ISSUE TITLE
RaGOO vs Ragout

### ISSUE THREAD

**Issue by fenderglass** [malonge/RaGOO#25]
Hi Michael,

Not an issue, but I rather want to state my opinion on this, and I am interested in hearing your thoughts as well.

As you might now, there is another tool for reference assembly called Ragout (https://github.com/fenderglass/Ragout). We initially published it in 2014 (https://academic.oup.com/bioinformatics/article-abstract/30/12/i302/388572) and another update in 2018 (https://genome.cshlp.org/content/28/11/1720.short). It is fairly popular in the community, e.g. we have >4k downloads within the last 1.5 years and 96 citations of the two papers combined. As far as I know, at least some authors of the RaGOO bioRxiv manuscript are aware of Ragout.

So as a result, we have two tools that are doing very similar jobs, and their names differ in two letters (that are not pronounced). I think this might cause a lot of confusion in the future. There might be obvious problems with packaging too (Bioconda and perhaps Linux distributions).

To reiterate, I am curious what are you thoughts on this? I am not criticizing any research aspects of your work. In fact, I am happy to see another tool that is faster and perhaps easier to use, I also appreciate that you have cited the Ragout2 paper in your preprint. It's just the naming that might cause the confusion for the genomics community in the future.

Best,
Mikhail

**Comment by malonge** [comment]
Hi there,

Thanks for bringing this up. Indeed, I am quite familiar with your great tool. And not to worry, I do not interpret your comment as a criticism.

Originally, I independently named the software, and only later did I learn of your tool and notice the name similarity. At that point, I thought it was too late to change the name. Unfortunately, that is especially true by now. It would just cause too many headaches and incompatibilities to change things now.

I can definitely tell you that we will avoid any technical naming/packaging conflicts like with Bioconda. If you see such a conflict, please let us know and we can fix it.

I agree that it has caused some confusion in the community which I do regret, though it was an honest mistake. I do believe/hope, however, that people will eventually be able to sort it out.

Thanks,
Mike

**Comment by fenderglass** [comment]
Thanks for clarification!
