### ISSUE TITLE
support input absolute path

### ISSUE THREAD

**Issue by cgjosephlee** [malonge/RaGOO#26]
Input absolute path in CLI will crashed at minimap2 stage because of using relative path in the script.

**Comment by malonge** [comment]
Yes this has been on the top of my todo list for a while now. I will let you know when this is ready.

Thanks

**Comment by malonge** [comment]
Hi there,

RagTag, the successor to RaGOO, is now available here:

https://github.com/malonge/RagTag

This feature is implemented in RagTag, and will likely not ever be implemented in RaGOO, which will eventually be deprecated. 

Thanks
