### ISSUE TITLE
AGP file

### ISSUE THREAD

**Issue by bistace** [malonge/RaGOO#28]
Hi,

I was wondering if RaGOO could generate an AGP file describing the location of each sequence after anchoring. I have tried each option but it doesn't seem that an AGP file can be generated. Could you please tell me if this is possible?

**Comment by malonge** [comment]
Hi there,

RaGOO comes with a script called `make_agp.py` just for this purpose. Hopefully, it is clear how to use it from the help message, but if it doesn't seem to be working, please let me know.

Thanks

**Comment by makakken** [comment]
hi there, i've tried to use make_agp.py but from the help message it's not clear to me how to use it. gap_size argument is probably 100 if i ran ragoo with default arguments before, right? but which files are the both files mentioned in the help message? first is the before-ragoo.fasta? second the after-ragoo.fasta? Sorry i do not have any background genome-sequencing, just running this programm as cumpouter scientist for a biologist friend ;)

**Comment by malonge** [comment]
Hi there,

RaGOO is no longer supported. You can use [RagTag](https://github.com/malonge/RagTag) instead, which automatically outputs AGP files.

Thanks
