### ISSUE TITLE
Manual order select contigs

### ISSUE THREAD

**Issue by elor77** [malonge/RaGOO#29]
Hi Michael
I'm using RaGOO to scaffold very long contigs of assemblies done with illumina polished ONT reads (~ 400 contigs in 400 Mb genome). Since some of the samples have been used in mapping populations, we have genetic linkage maps which we can use as another reference for contig grouping and order.

My question is whether there is some way of 'imposing' scaffolding grouping and order manually for some of the contigs?

**Comment by malonge** [comment]
Hi there,

If I understand you correctly, you would like RaGOO to give you an initial ordering and orientation, but you would like to manually adjust it based on scaffolding info from your linkage map?

RaGOO creates the final pseudomolecyles based on the txt files in the `groupings` and `orderings` directories in `ragoo_output`. If those directories already exist when running RaGOO, they will not be remade/altered. 

So you can run RaGOO. Then manually adjust the order of the rows in the txt files, then run RaGOO again. If this sounds like what you need, let me know and I can give you some more details.

Incidentally, someday, it would be nice to add linkage map info integration as an automatic feature. I'd have to think about that some more ...

**Comment by elor77** [comment]
That's exactly what I mean, thanks.
So I'd just change the order manually, what about the confidence scores, just insert any value?
(whats the second column in orderings?)
`#groupings_chr08`
`contig_1        0.6767095404376283`
`contig_106      0.7943104928987869`
`contig_109      0.4605244346994706`
`contig_110      0.8586165158988733`

`#orderings_chr08`
`contig_1        -       0.8894757478607838      1.0`
`contig_30       +       0.12896893648317712     0.9942700131195993`
`contig_129      -       0.14143580258785673     0.9961028025025576`
`contig_151      -       0.027990274798635948    0.9910927678315062`

A feature for linkage map would be nice, but you'd have to figure out how to automatically weigh conflicting results - unless the linkage map is flawless..  

BTW I find the confidence scores very useful so thanks for that!

**Comment by malonge** [comment]
Ok great I can give you some more details to help it go smoothly.

- The second column of the orderings file is orientation of the contig. 
- Confidence scores are not needed for the final scaffolding, but of course, they may be invalidated depending on the edits.

- A contig must be in the orderings and groupings file for the same reference chromosome. So, given your example above, if you move `contig_1` from `chr08_contigs.txt` to `chr09_contigs.txt` you will also need to move it from `chr08_orderings.txt` to `chr09_orderings.txt`

- The order does not matter in the groupings file, but the order of the orderings file matters, and that is, in-fact, how the final ordering is determined. If you want `contig_1` to be the first contig of the pseudomolecules, in reverse orientation, place `contig_1 - 0.8894757478607838 1.0` as the very first line in the orderings file. If you want it last in the pseudomolecules, put it as the very last line in the file.

- Scores may be invalidated depending on what you do with the contig. If a contig stays assigned to the same reference chromosome, its grouping and location score remains the same. If the orientation stays the same, the orientaiton score also stays the same. But like I said, you don't need the scores to be valid for the scaffolder to work. It is just reported for the user.

I hope that helps. If I have forgotten anything or if something goes wrong, let me know.

Thanks,
Mike

**Comment by malonge** [comment]
Actually, now that I look at the code again, pseudomolecules are established just from the orderings files. So you can also change groupings files for consistency, but that is not actually needed for scaffolding.

**Comment by elor77** [comment]
Thanks Mike, I'll let you know how it goes.

**Comment by elor77** [comment]
Changed the orderings file according to the genetic map order worked peprfectly
Thank you!

**Comment by malonge** [comment]
Hi there,

Yes, sorry about that. I think this would be a fairly simple fix to enable the option to keep preexisting orderings files. Would you like me to add that? I see you closed the issue again.

**Comment by elor77** [comment]
Yes please, I closed the issue by mistake..

**Comment by malonge** [comment]
Ok so I believe there should be a working solution in the "keep_orderings" branch of the github repo. Could I trouble you to install this branch and see how it goes? Just use "-O" to ensure that preexisting orderings files will not be overwritten. 

I think I will probably hold off on adding this to the master branch until I release the next version. I just want to double-check everything before I do that. But we can work on this branch for a short-term solution.

**Comment by malonge** [comment]
btw, perhaps you have already done this, but I would suggest making a backup copy of the orderings file since I understand you may have taken a decent amount of time to manually order things. I apologize that I was wrong in the first place and your file got overwritten.

**Comment by elor77** [comment]
Thank! I'll try later today or tomorrow and let you know if it works - it's no trouble at all.
Everything's backed up -  no worries :)
This will actually helps a lot -  I'd like to figure out how much of  the linkage based order is relevant when applying it just to one of the parents - since i'm not sure how large SVs in the both parents are inherited and might affect the linkage based order...

**Comment by malonge** [comment]
Hi there,

Were you ever able to confirm if the orderings files are retained? Also (FYI) the ordering files in the forthcoming v2 of the software will certainly be retained to enable manual ordering.

**Comment by elor77** [comment]
No Michael, sorry.
Haven't gotten back to that yet..
Thanks for following up.
I'll be sure to check it this week and let you know.
Thanks for the update.. It'll be useful!
Elad

**Comment by malonge** [comment]
Hi there,

No worries - please take your time. I am just reviewing outstanding issues in anticipation of the next version release.

**Comment by malonge** [comment]
Hi there,

RagTag, the successor to RaGOO, is now available here:

https://github.com/malonge/RagTag

For RagTag, AGP files are used as intermediate files defining the ordering and orienting of contigs. These files will not be overwritten (unless requested) and thus can be adjusted for manual ordering and orienting. 

Thanks

**Comment by elor77** [comment]
Nice!! thanks for the update.
