### ISSUE TITLE
Pass arguments to minimap2 (especially `-I` for large genomes)

### ISSUE THREAD

**Issue by lucventurini** [malonge/RaGOO#30]
Dear @malonge , 
                              many thanks for developing `RaGOO`. We would like to use it on our research on wheat, but I have hit a (very minor) roadblock, that is that it is not possible to give extra-command line arguments to `minimap2`. This is particularly important for wheat because the genome is six times larger than human and this conflicts with the default index size of `minimap2` (ie 4Gbps). 

I have hard-coded the modification in my copy of the code, but a less brittle solution might be useful for the tool.

Kind regards

**Comment by malonge** [comment]
Hi there,

I agree this would be a handy feature. I will add it to my TODO list for RaGOO.

FYI, another interim solution is to produce your own alignments, then change their name to `contigs_against_ref.paf`. If a file with that name is in `ragoo_output`, regardless of how it was produced, RaGOO will not replace it, and will use it for scaffolding.

Sometimes I do that when I want to use nucmer alignments. I make my delta file, convert that to paf with `paftools`, then plug that in.

**Comment by lucventurini** [comment]
Thank you for the suggestion. I will most probably use it if the results look strange, to experiment with eg minimum alignment scores.

**Comment by malonge** [comment]
Yes, personally, I have never gotten Minimap2 to worker on larger plant genomes. I would be very curious to know what parameters you set to get it to work.

Or, you can use nucmer and set `-l` and `-c` to pretty large numbers, if your assembly is contiguous enough.

**Comment by malonge** [comment]
Hi Luca,

RagTag, the successor to RaGOO, is now available here:

https://github.com/malonge/RagTag

This feature is implemented in RagTag, and will likely not ever be implemented in RaGOO, which will eventually be deprecated.

I would also like to thank you for all of your helpful suggestions, many of which made their way into RagTag.

Thanks,
Mike
