### ISSUE TITLE
Misassembly Correction

### ISSUE THREAD

**Issue by mictadlo** [malonge/RaGOO#31]
Hi,
I would like to use ONT reads with RaGOO's Misassembly Correction step. We have 7x ONT reads and 50x Illumina pair-end reads. What would be the best way to error-corrected these long reads?

Thank you in advance,

Michal

**Comment by malonge** [comment]
Hi there,

Honestly, with only 7X, it is not enough coverage even if it is error corrected. I would just go ahead and use your Illumina reads instead. 

- Mike

**Comment by malonge** [comment]
I am going to close this issue, though please feel free to reopen it if anything comes up.

I would also encourage you to use RagTag for any future analysis:

https://github.com/malonge/RagTag

RagTag is the successor of RaGOO and it is much improved.

Thanks,
Mike
