### ISSUE TITLE
Preventing Ragoo output to be similar too reference

### ISSUE THREAD

**Issue by mictadlo** [malonge/RaGOO#36]
Hi,
I ran `ragoo.py -t 8 -g 100 -s -b -C  contigs.fa refence.fa`. The `reference.fa` contains a 70bp insertion which is correct. On the other hand, `contigs.fa` (wild type) does not contain it which is correct, too. 

However, Ragoo inserted the 70bp from the `reference.fa` to its output which I would like to prevent. Is there a better setting in Ragoo to prevent it from happening?

Thank you in advance,

Michal

**Comment by malonge** [comment]
Hi there,

By design, RaGOO does not insert any sequence (other than gaps between contigs), nor does it remove any sequence. At most, it will break contigs since you are using `-b`. 

Is your observation because you don't see a deletion in the assemblytics output file?

**Comment by mictadlo** [comment]
Hi,
We have PCR sequences of a gene region for different wild types. The gene sequences from both Ragoo and reference contained the same insertion after we compared them. However, when we compared both Ragoo and contig assembly, then the last one does not include the insertion.  

Do you think that `-R` and `T` could provide a different outcome?

Thank you in advance,

Michal

**Comment by malonge** [comment]
Hi Michal,

The only thing that I can think of is that perhaps the `-b` option is breaking this contig and there is another smaller contig somewhere else in the assembly that is then getting placed in betwee, The best way to test this would be to run RaGOO without any chimera/misassembly correction. Just order and orient the contigs as they are.

Let me know how that goes. I can guarantee that the default output of RaGOO (no `-b` or `-T -R`) is just an ordering and orienting of the initial set of contigs, i.e. no addition, subtraction or breaking of sequence.

**Comment by mictadlo** [comment]
Hi,
Thank you. It worked.

Best wishes,

Michal

**Comment by malonge** [comment]
Glad to hear!
