### ISSUE TITLE
Question: contig names in output

### ISSUE THREAD

**Issue by reubwn** [malonge/RaGOO#37]
Hello,

Just a quick question about the contig names in the output `ragoo.fasta` file - some of them have inherited the reference scaffold names while others remain unchanged (apart from the "_RaGOO" suffix). Is it simply the case that any contigs aligning to a given reference sequence are then stitched together and collectively inherit that reference sequence name?

Thanks in advance, and also for the nice piece of software.

Cheers,
Reuben

**Comment by malonge** [comment]
Yes, you got it right. I assume you ran RaGOO with `-C`, otherwise all of the unplaced sequence would land in `>Chr0_RaGOO`.
