### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by shehongbing** [malonge/RaGOO#38]
This is the python3 in my linux

python3
Python 3.6.6 (default, Mar 29 2019, 00:03:27)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.

And when I install the software:  python3 setup.py install
it occur:

$ python3 setup.py install
/usr/lib/python3.6/site-packages/setuptools/dist.py:398: UserWarning: Normalizing 'v1.1' to '1.1'
  normalized_version,
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.6'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

**Comment by malonge** [comment]
Hi there,

perhaps you don't have permission to install there? Can you try installing in a virtualenv? Or perhaps in a conda env?

To be clear, I don't mean to install with conda directly, since that is currently not supported. But if you have conda installed, you can install RaGOO there manually. Like this:

`~/anaconda3/bin/python setup.py install`

Then, `ragoo.py` will be in `~/anaconda3/bin/`

**Comment by shehongbing** [comment]
Thank you very much

**Comment by shehongbing** [comment]
Hi, 
I think I'm install ragoo correctly, but when I press:
python ragoo.py,   threes something wrong

raceback (most recent call last):
  File "/data/pub/shehb/miniconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/data/pub/shehb/miniconda2/lib/python2.7/site-packages/numpy/core/multiarray.py", line 13, in <module>
    from . import overrides
  File "/data/pub/shehb/miniconda2/lib/python2.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dynamic module does not define init function (PyInit__multiarray_umath)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ragoo.py", line 10, in <module>
    from ragoo_utilities.ReadCoverage import ReadCoverage
  File "/data/pub/shehb/soft/RaGOO-master/ragoo_utilities/ReadCoverage.py", line 3, in <module>
    import numpy as np
  File "/data/pub/shehb/miniconda2/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/data/pub/shehb/miniconda2/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /data/pub/shehb/miniconda2/envs/python3.4/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: dynamic module does not define init function (PyInit__multiarray_umath)

**Comment by shehongbing** [comment]
And I also install the python3.4 using condo 

conda create -n python3.4 python=3.4
conda activate python3.4

**Comment by shehongbing** [comment]
Oh, I  solve it. Thank you
