### ISSUE TITLE
SV types from RaGOO output as VCF

### ISSUE THREAD

**Issue by evolgen** [malonge/RaGOO#4]
Hi Michael, 

Thanks for the really cool tool, the speed up with the current version is awesome.
I have been RaGOO for scaffolding and calling SVs between sister species of lizards. 

I tried to use the SURVIVOR bedtovcf on the assemblytics_out.Assemblytics_structural_variants.bed with types as DEL/INS/DUP/INV/TRA/BND.
The TRA and BND both don't work. Additionally, I get two groups of outputs :
(1) identical between DEL/INS/DUP/INV - the name of each type is distinct but the same results including coordinates
(2) identical between TRA/BND - shown as type NA

Is there something I am missing here or is the output conversion currently under development?

**Comment by malonge** [comment]
Hi there,

That sounds like a fun project. Try using the `convertAssemblytics` module of SURVIVOR. Please note that if you haven't already, the last two columns of the bed file need to be removed from this. Those two columns are the percent overlap with a gap. I would filter based on this, then remove those columns.

In the somewhat near future, but not sure when, I think I just want to automatically convert to VCF.

Thanks,
Mike

**Comment by malonge** [comment]
Please also refer to the [SV calling wiki page](https://github.com/malonge/RaGOO/wiki/Calling-Structural-Variants) for more details on this.

**Comment by evolgen** [comment]
Thanks a ton Mike, sorry I overlooked that wiki. The last two columns were removed and filtered on atleast 75% overlap. All the SVs detected were either INS/DEL. DUP/INV were detected from both read alignments (illumina and PacBio) and my own pipeline from minimap2 genomic alignments - does RaGOO have strict criterion for other SV types?

**Comment by malonge** [comment]
Glad to hear that worked. RaGOO uses and integrated versin of Assemblytics, which only calls insertions and deletions. In the wiki page, I also talk about paftools, which also only calls insertions/deletions.

Read alignment based variants callers, especially with long reads, will capture these other types of variants, though there are fewer tools which call such alignments with assembly alignments. [Here is one tool that I have seen](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4690232/), though I have not tried it out myself. I would be interested to see how you call variants from Minimap2 alignments if you are willing to share your code.

Thanks

**Comment by evolgen** [comment]
Oh - good to know. I never tested out other callers based on assembly alignments. I would be glad to share the pipeline - I will email you the snippets and workflow (haven't posted them on github since they are not extensively tested)

**Comment by malonge** [comment]
Cool thanks!

malonge11@gmail.com
