### ISSUE TITLE
RuntimeError when turing on the SV calling option

### ISSUE THREAD

**Issue by JunpengShi** [malonge/RaGOO#42]
Hi Micheal,
     I encountered an RunTimeError when turning on the Assemblytics option to map the pseudomolecules back to the reference and call SVs:
     Fri Dec 13 21:10:54 2019 --- Running : minimap2 -ax asm5 --cs -t12 ../.././Zm-Mo17-REFERENCE-CAU-1.0.fa ../ragoo.fasta > pm_against_ref.sam 2> pm_contigs_against_ref.sam.log
/bin/bash: line 1: 35791 Aborted                 minimap2 -ax asm5 --cs -t12 ../.././Zm-Mo17-REFERENCE-CAU-1.0.fa ../ragoo.fasta > pm_against_ref.sam 2> pm_contigs_against_ref.sam.log
Traceback (most recent call last):
  File "/home/lailab/shijunpeng/software/RaGOO-master/ragoo.py", line 754, in <module>
    align_pms(minimap_path, t, reference_file)
  File "/home/lailab/shijunpeng/software/RaGOO-master/ragoo.py", line 439, in align_pms
    run(cmd)
  File "/home/lailab/shijunpeng/software/RaGOO-master/ragoo_utilities/utilities.py", line 25, in run
    raise RuntimeError('Failed : %s ' % cmnd)
RuntimeError: Failed : minimap2 -ax asm5 --cs -t12 ../.././Zm-Mo17-REFERENCE-CAU-1.0.fa ../ragoo.fasta > pm_against_ref.sam 2> pm_contigs_against_ref.sam.log

   Possibilly due to the --cs option with out a build-in string in RaGOO scripts that disabled the -t option of minimap2?

Best Regards,
Junpeng

**Comment by malonge** [comment]
Hi there,

So the minimap2 command failed for some reason. From within `pm_alignments`, could you try to run that same `minimap2` command manually and report what happens?

Thanks

**Comment by JunpengShi** [comment]
It seems that the memory was insufficient when manually ran the command in the pm_alignments folder:

**Comment by JunpengShi** [comment]
It seems that the memory was insufficient when I ran the command: minimap2 -ax asm5 --cs -t12 ../.././Zm-Mo17-REFERENCE-CAU-1.0.fa ../ragoo.fasta > pm_against_ref.sam 2> pm_contigs_against_ref.sam.lo manually in the pm_alignments folder.

I'm comparing two maize genomes in a core with 1Tb RAM and 128 threads. Possibily due to the asm5 model that requires ultra large RAM?

Best,
Junpeng

**Comment by JunpengShi** [comment]
Another thing to note was that the largest maize chromosome was ~300 Mb in the reconstructed ragoo.fasta file. Such a untra large query sequence may exhaust the minimap2 that out of memory? It works when I align the contigs against the same reference.

**Comment by malonge** [comment]
I will consider this to be related to Minimap2 rather than RaGOO. In the future, we will add the ability to pass any command-line arguments to minimap2. I am not sure if that will help, but it at least will provide some flexibility.
