### ISSUE TITLE
Maximum number of breaks per contig

### ISSUE THREAD

**Issue by gbdias** [malonge/RaGOO#43]
Hi @malonge,

I have tested RaGOO with read alignment-based misassembly correction for the first time and noticed that some contigs are broken in more than one place.

Here is an example of a contig that was broken into 4 parts after a single round of RaGOO:
```
tig00000329|arrow|pilon_misasm_break:0-735947
tig00000329|arrow|pilon_misasm_break:735947-1296254
tig00000329|arrow|pilon_misasm_break:1296254-2273490
tig00000329|arrow|pilon_misasm_break:2273490-3198721
```

The parameters I used were:
```
ragoo.py -t 20 -R ../correctedReads.fasta -T corr -i 0.7 -c 1000000 -d 1500000 -g 100 -C "$ASMN" "$REFN"
```

I was just wondering if the 1 inter- and 1 intra-chromosomal break maximum is only in place if not using -R.

Thanks

**Comment by malonge** [comment]
Hi there,

Yes you are correct. -R will break everything in a single pass, whereas -b has the maximums that you described. I should probably make that clear in the wiki.

**Comment by malonge** [comment]
I should add that I think -R should always be used over -b, if one has the requisite data.

**Comment by gbdias** [comment]
Got it. Thanks for clarifying!
