### ISSUE TITLE
Super-scaffolding two genome drafts

### ISSUE THREAD

**Issue by enormandeau** [malonge/RaGOO#44]
Would there be a way to use RaGOO to use two draft genomes with already interesting scaffold N50s and create a single super-scaffolded assembly?

#### Bogus example
```
Genome 1:
-----  --------------     --------------  ----  ------
Genome 2:
------------- ---- ----------------   ------------
Super scaffolds:
------------------------------------------------------
```

**Comment by enormandeau** [comment]
This is a very common scenario I think, although it may not be a case that RaGOO is designed to solve.

**Comment by enormandeau** [comment]
Alternatively, given two such draft genomes, how would you proceed to create a super-scaffolded assembly? (asking for advice ;) )

**Comment by malonge** [comment]
Hi there,

It seems like you are describing a "reconciliation" type of procedure. There are other tools that address this more directly, like [Ragout](https://github.com/fenderglass/Ragout).

For RaGOO, something always has to be considered the "reference". So if one of the assemblies is much for contiguous than the other, you could use that one as the "reference".

**Comment by enormandeau** [comment]
Thank you for the suggestion. If you know of any other such tool, I'd be happy to know. Otherwise, please feel free to close this issue.

**Comment by malonge** [comment]
maybe this will be of use:

https://genomebiology.biomedcentral.com/articles/10.1186/s13059-017-1213-3

**Comment by enormandeau** [comment]
I'm not sure I ever came across this paper. Thank you.
