### ISSUE TITLE
Pseudomolecules creation step error

### ISSUE THREAD

**Issue by Yedomon** [malonge/RaGOO#45]
Greetings of the season.

I ran RaGoo on a Masurca assembly of short reads data with a chromosomal-scale reference genome.

I got this error

Thu Jan 23 09:53:29 2020 --- Reading alignments
Thu Jan 23 09:53:30 2020 --- Assigning contigs
Thu Jan 23 09:53:30 2020 --- Ordering and orienting contigs
Thu Jan 23 09:53:32 2020 --- Creating pseudomolecules
Traceback (most recent call last):
  File "ragoo.py", line 742, in <module>
    create_pseudomolecules(contigs_file, all_unique_contigs, g, make_chr0)
  File "ragoo.py", line 339, in create_pseudomolecules
    remaining_contig_headers.pop(remaining_contig_headers.index('>' + line[0]))
ValueError: '>gi|1046489213|gb|MBSK01000787.1|' is not in list

How can I fix this problem?

Thank you.

Here are the assembly stats

Assembly                    final.genome.scf
# contigs (>= 0 bp)         13835
# contigs (>= 1000 bp)      7205
# contigs (>= 5000 bp)      4649
# contigs (>= 10000 bp)     3841
# contigs (>= 25000 bp)     2730
# contigs (>= 50000 bp)     1675
Total length (>= 0 bp)      250495326
Total length (>= 1000 bp)   247455423
Total length (>= 5000 bp)   241625893
Total length (>= 10000 bp)  235851007
Total length (>= 25000 bp)  217286364
Total length (>= 50000 bp)  179069540
# contigs                   9145
Largest contig              780203
Total length                248822296
GC (%)                      34.83
N50                         85631
N75                         44887
L50                         851
L75                         1835
# N's per 100 kbp           0.00

**Comment by malonge** [comment]
Hi there,

`remaining_contig_headers` is simply a list of every contig in the draft assembly. RaGOO goes through every "ordering" file, puts the sequence in place, and makes a note that the contig is no longer "remaining". This is how RaGOO knows which contigs are unplaced i.e. anything left in `remaining_contig_headers`.

I think the best thing to do is to make a samtools fasta index file for the draft assembly. Then, grep ">gi|1046489213|gb|MBSK01000787.1|"  to see if that contig header is present in the fasta index.

**Comment by Yedomon** [comment]
Thanks a lot. I solved the problem.
Best Regards.

**Comment by malonge** [comment]
Glad to hear!
