### ISSUE TITLE
Gap filling with RaGOO

### ISSUE THREAD

**Issue by ViriatoII** [malonge/RaGOO#48]
Hey,

I heard RaGOO is also good for gap filling. Is that so? 

Can I use my scaffolded assembly as reference and NanoPore reads as contigs to map? Or perhaps with the -R parameter?

Cheers,
Ricardo

**Comment by malonge** [comment]
Hi there,

I wouldn't recommend using RaGOO for this purpose. Ultimately the query sequences will all be concatenated in some order which is not what you are looking for.

**Comment by ViriatoII** [comment]
Thanks!
