### ISSUE TITLE
Structural Variants Calling 

### ISSUE THREAD

**Issue by MehmetGoktay** [malonge/RaGOO#49]
Hi Mike,

In Assebmlytics website it is highly not recommended to have NNNNN's between contigs to anchor them. But ragoo does scaffolding to call svs via assemblytics. Is this an issue or did you walked around it somehow. 

Also are you planning to make a parameter to set minimum and maximum size of SVs instead of having default values which are 50 and 10kb?

Mehmet

**Comment by malonge** [comment]
Hi there,

We do something a little funky. Unlike native Assemblytics, we get alignments with Minimap2 which is much more robust to gaps in the sequence.

Of course, you could just run Assemblytics separately, in which case I would follow their advice and break your assembly at N's before aligning with Nucmer.

As for your second question, you can specify a minimum (-a) and a maximum (-f) SV size via command line. I currently have suppressed these options in the help message, though I don't remember why. I will add documentation for them in future updates.
