### ISSUE TITLE
 RaGOO Chr > reference Chr

### ISSUE THREAD

**Issue by mazepago** [malonge/RaGOO#50]
Hello,

I am trying to use RaGOO to map a frog draft assembly (4.6G) of another 30Mya diverged high quality assembly (4.4G), RaGOO is doing a great job for chr1-10 except the strange pattern i observe for the chr11-13: the constructed Chr are larger than the reference. Would appreciate any suggestion how to deal with that.

<img width="400" alt="Screen Shot 2020-02-06 at 2 49 32 PM" src="https://user-images.githubusercontent.com/30182231/73942785-f3081c00-48ef-11ea-9916-0601c50a7686.png">

**Comment by malonge** [comment]
Hi there,

All I can say is that, for some reason, many of your contigs are preferentially aligning to those chromosomes. Given the distance between the two genomes, I suppose there could be a variety of biological reasons why this could happen. For example, are you sure these even have the same # of chromosomes?

Certainly, this would be outside the usual scope of RaGOO which was designed for closely related genomes. Though you can use any two genomes, this may indicate that they are just too diverged to expect accurate scaffolding.
