### ISSUE TITLE
Lift-over reference annotations to ordered contigs

### ISSUE THREAD

**Issue by charlesfeigin** [malonge/RaGOO#51]
Hi,

The liftover.py script is able to use the orderings to lift-over annotations from the input contigs onto the newly-ordered contigs (pseudomolecules). Is there a straightforward way to use that ordering information to take annotations from the reference genome and apply them to the ordered contigs? Thanks!

**Comment by malonge** [comment]
Hi there,

You are describing a slightly different but much harder task. There are, however, a few tools that can do this, though imperfectly. 

Firstly, you can use [paftools.js liftover](https://github.com/lh3/minimap2/tree/master/misc). This will perform whole-genome alignment, then try to lift-over genes based on those alignments.

Also, a colleague of mine wrote a great tool that maps individual genes onto an assembly to perform lift-over. That is called [geneLift](https://github.com/srividya22/geneLift) and we have used it with a lot of success.

Hope that helps!

**Comment by charlesfeigin** [comment]
Extremely helpful, thanks so much!
