### ISSUE TITLE
Differentiation Pseudomolecules

### ISSUE THREAD

**Issue by mwylerCH** [malonge/RaGOO#52]
Hi, 
RaGOO is smoothly working and is quite handy. 
But of course I would still make a small remark: is there any direct way to know the origin from a piece of the pseudomolecule? In other words: what is exactly coming from the reference and what from the supplied new scaffolds?
Maybe the usage of upper and lower letters or converting the remaining reference to bases to N?
Many thanks

**Comment by malonge** [comment]
Hi there, 

The pseudomolecules are only comprised of the contigs/scaffolds. No part of the pseudomolecules comes from the reference genome. 

This is by design. The pseudomolecules are just and ordered and oriented version of the contigs, with gaps for padding placed between adjacent contigs.
