### ISSUE TITLE
Targeted assembly. Whole genome or target area as reference?

### ISSUE THREAD

**Issue by ViriatoII** [malonge/RaGOO#54]
Hi, 

I guess this is very dependent on Minimap2, but what do you recommend to use as a reference for a targeted scaffolding: The whole reference genome or only the target region I'm trying to assemble?

I have done targeted sequencing. My problem is that I'm not 100% sure all my reads belong to the target region. In fact, once I use Ragoo with the whole reference genome, most of my reads/assembled contigs are not scaffolded in my target region:

(my target region is a 10Mb part of  Chr. 10)

original reads | assembled contigs (canu) | Mapped to
-- | -- | --
2 225 | 3 | chloroplast
562 | 10 | mitochondria
6 961 | 117 | Chr1
6 915 | 138 | Chr2
5 721 | 105 | Chr3
4 837 | 80 | Chr4
5 399 | 99 | Chr5
3 365 | 66 | Chr6
3 138 | 52 | Chr7
3 524 | 56 | Chr8
2 929 | 40 | Chr9
22 510 | 190 | Chr10
2 814 | 20 | ChrUN
70 900 | 976 | Total

I'm noticing that when using the targeted region only as reference, more things belong there, but I'm unsure if that is just forced..

Belongs to | raw reads | assembled contigs (canu)
-- | -- | --
Unmapped | 20 737 | 378
Target region | 51 354 | 598

Hope you can advise me,
Ricardo

**Comment by malonge** [comment]
Hi there,

All ragoo is going to do is concatenate your contigs somehow, reverse complementing where needed. Keeping that in mind, I would recommend pre-filtering your contigs such that ragoo is only scaffolding contigs that represent your target region. Then, these will be ordered and oriented with respect to each other.

In theory, at that point, you could use the whole genome or just the targeted portion of the reference genome to guide the scaffolding. Perhaps focusing on the targeted region will remove potential repetitive alignments. But you could try both and see how it goes.
