### ISSUE TITLE
Liftover reference gff

### ISSUE THREAD

**Issue by soungalo** [malonge/RaGOO#55]
This is a feature request - would be nice if I could provide RaGOO with the **reference** gff, and genes would just be lifted over to the pseudomolecules generated by RaGOO.

**Comment by malonge** [comment]
Hi there,

Though this is slightly beyond the scope of RaGOO, I do have two suggestions for a tool, written by my colleague, that does this.

- [geneLift](https://github.com/srividya22/geneLift)
