### ISSUE TITLE
How reliable these results are?

### ISSUE THREAD

**Issue by francicco** [malonge/RaGOO#6]
Hi,

I did a couple of tests and it look like there is a lot of scaffolding going on

There are 10Mya difference between the assembly to scaffold and its reference.

```
Reference: EisaPacBio.assembly.v1.0.fasta
____________________________
N50: 1613086.0
Number of contigs: 580
Longest contig: 6085293
Genome length: 401008328
```
```
My query: Etal.curated.fasta
____________________________
N50: 39539
Number of contigs: 25749
Longest contig: 401059
Genome length: 461252547
```
```
The output: ragoo.fasta
____________________________
N50: 2449116
Number of contigs: 504
Longest contig: 97232201
Genome length: 463829447
```
and this is the way I'm runnig RaGOO

`python ragoo.py -t 32 -i 0.5 -b Etal.curated.fasta EisaPacBio.assembly.v1.0.fasta`

How reliable is this result?

Thanks
Great tool!
F

**Comment by malonge** [comment]
Hi there,

Thanks for the question. Please take a look at the [FAQ](https://github.com/malonge/RaGOO/wiki) where I address this.

There are basically two questions: 

1. How will does RaGOO construct pseudomolecules that are syntenic with the reference.

This is the easiest to evaluate. I would align the ragoo.fasta file back to the reference and look at the synteny plots (dot plots). The [confidence scores](https://github.com/malonge/RaGOO#output-files) can also help with this. 

2. How accurately do the pseudomolecules represent the true chromosomal structure.

This is harder to evaluate. Generally speaking, the results should be most accurate for species that have shared chromosomal structure (closely related species). The best way to see how reliable the results are is to validate with some independent data. In our preprint, we used Hi-C for this.

**Comment by malonge** [comment]
Looking at your results a little more, which pseudomolecule is of length 97232201 bp? Is that chr0? Two other things stand out. Firstly, your assembly is quite a bit larger than the reference. Is that expected? Also, you set `-i` to be fairly high. You could probably stand to lower that a little. I have a feeling a good chunk of your assembly is ending up in chr0.
