### ISSUE TITLE
Input as scaffolds

### ISSUE THREAD

**Issue by tk2** [malonge/RaGOO#64]
Hi,
We are quite keen to try RaGOO to do the last step in our assembly pipeline to produce the final chromosome ordering. We have pacbio contigs that were then scaffolded using mate-pairs and optical maps. Can we give these scaffolds as input to RaGOO? Or does it strictly only accept contigs?

Thanks,
Thomas

**Comment by malonge** [comment]
Hi there,

You can absolutely use scaffolds as input. That should work just fine.

Thanks
