### ISSUE TITLE
RuntimeWarning: Mean of empty slice

### ISSUE THREAD

**Issue by XuewenWangUGA** [malonge/RaGOO#65]
installed via python_3/3.5.0
Input file is the working directory same as the reads file, contigfile and refseqfa file
my command:
python3 $tooldir/ragoo.py  -t $nthrd  -R $reads -T corr -m $minimap2dir $contigfile $refseqfa

error: 
on May 18 12:26:53 2020 --- Misassembly correction has been turned on. This automatically inactivates chimeric contig correction.
Mon May 18 12:26:53 2020 --- Reading alignments
Mon May 18 12:26:53 2020 --- Aligning raw reads to contigs
Mon May 18 12:26:53 2020 --- Computing contig coverage
/software/7/apps/python_3/3.5.0/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/software/7/apps/python_3/3.5.0/lib/python3.5/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Mon May 18 12:27:17 2020 --- Assigning contigs
Mon May 18 12:27:17 2020 --- Ordering and orienting contigs
Mon May 18 12:27:17 2020 --- Creating pseudomolecules
Mon May 18 12:27:26 2020 --- goodbye

Question:
1) the parameter "-m " should use the path or path/miniapp2. I tried both, and get the same error
2) What cause the  error information? The memory and threads are enough.
Thanks.

**Comment by malonge** [comment]
Hi there,

What do you PAF intermediate files look like? Are they empty?

Thanks

**Comment by XuewenWangUGA** [comment]
Yes.
Ths PAF file is empty.


Xuewen

________________________________

**Comment by malonge** [comment]
This might be a simple fix: RaGOO will not overwrite existing intermediate files in order to save on compute. Please try deleting those files (if not the whole output directory just to be safe) and re-run.

Thanks

**Comment by XuewenWangUGA** [comment]
Michael,

Thank a lot. I am trying after deleting previous generated files. Now it seems working.


Xuewen

________________________________

**Comment by malonge** [comment]
great - I will close the issue for now, but please reopen if any problems arise. 

Thanks
