### ISSUE TITLE
Why BUSCO reports fewer genes after RaGOO?

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [malonge/RaGOO#66]
Hey there!
I used:
`python3 ragoo.py contigs.fasta reference.fasta`
Then, surprisingly BUSCO reported fewer genes after RaGOO (Table). One complete gene and 4 fragmented genes lost :-( .
Table. 
```
Genes         Contigs  Contigs&RaGOO
Complete sing    4380           4379
Complete dupl       7              7
Fragmented         13              9
Missing            15             20
```
Is that because of contig orienting & ordering? Or another reason?
How to set RaGOO parameters to save these genes?
Thanks in advance!

Cheers,
Ural

**Comment by malonge** [comment]
Hi there,
The scaffolds are just supposed to be ordered and oriented contigs with gaps for padding. Perhaps you should verify that this is true. Or I could do that for you if you are willing to share your data.

If this is indeed the case, then I suppose the variable results are the result of some BUSCO heuristic - probably specific to Agustus would be my uninformed guess.

If that is the case, then I wouldn't necessarily consider the original BUSCO results more accurate. If strictly ordering and orienting contigs changes the BUSCO results, then as far as I know, either result could be more accurate.

But it is very important to ensure the sequence conservation guarantee. In v2 I will have automated tests for this. But for now, I am happy to test that for you.

**Comment by Ural-Yunusbaev** [comment]
Hi Michael,
Thank you for your prompt response 
I shared my files at https://drive.google.com. Please check your mail in google.com
I would be grateful to you for help with RaGOO.

Cheers,
Ural

**Comment by malonge** [comment]
Hi there,

Using your data I was able to confirm that the final scaffolds are strictly an ordering an orienting of the input contigs. In other words, no sequence was lost or gained. Therefore it must be some BUSCO heuristic that is causing the discrepancy.

Thanks

**Comment by mschatz** [comment]
Yes, Ive noticed this too that the BUSCO output is not completely stable in
that reordering the contigs in a fasta file (but not changing the sequence
at all) can change the scores a bit. I dont have a deep understanding of it
other than there must be some heuristics involved that are sensitive to how
the data are internally batched

Mike

**Comment by Ural-Yunusbaev** [comment]
Thank you!
