### ISSUE TITLE
KeyError during liftover

### ISSUE THREAD

**Issue by Asutu** [malonge/RaGOO#7]
Hi,

I aligned a set of contigs to a reference genome of the same species with RaGOO, and while trying to run the liftover utility afterwards I get a `KeyError` exception. The commands I used were as follow:

```
ragoo.py -t 6 -g 100 contigs.fasta reference.fna   # runs OK
ls ragoo_output/orderings/* > orderings.fofn   # runs OK
samtools faidx contigs.fasta   # runs OK
lift_over.py -g 100 reference.genes.gff orderings.fofn contigs.fasta.fai > genes.lifted-ragoo.gff
Traceback (most recent call last):
  File "/Users/pmca/local/biosoft/bin/lift_over.py", line 4, in <module>
    __import__('pkg_resources').run_script('RaGOO==1.2', 'lift_over.py')
  File "/Users/pmca/Software/assemblers/RaGOO_venv/66ef904/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/pmca/Software/assemblers/RaGOO_venv/66ef904/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/pmca/Software/assemblers/RaGOO_venv/66ef904/lib/python3.6/site-packages/RaGOO-1.2-py3.6.egg/EGG-INFO/scripts/lift_over.py", line 84, in <module>
KeyError: 'NC_024238.1'
```

I don't think I swapped the contigs-reference order in the commands, so not sure what might be causing this error.

I also checked the output files and everything seems to be present. This reference scaffold only has a single alignment but I wouldn't guess this to be the cause of the issue.

```
$ cat reference.fna | grep NC_024238.1
>NC_024238.1 Some species mitochondrion, complete genome
$ cat reference.genes.gff | grep NC_024238.1
##sequence-region   NC_024238.1 1 16538
NC_024238.1	RefSeq	tRNA	1	69	.	+	.	ID=rna48629;gbkey=tRNA;product=tRNA-Phe
NC_024238.1	RefSeq	exon	1	69	.	+	.	ID=id635338;Parent=rna48629;gbkey=tRNA;product=tRNA-Phe
# ... and more GFF lines
$ cat orderings.fofn | grep NC_024238.1
ragoo_output/orderings/NC_024238.1_orderings.txt
$ ls -l ragoo_output/orderings/ | grep NC_024238.1
-rw-r--r--  1 pmca  staff     31  5 Mar 22:10 NC_024238.1_orderings.txt
$ ls -l ragoo_output/groupings/ | grep NC_024238.1
-rw-r--r--  1 pmca  staff      8  5 Mar 22:10 NC_024238.1_contigs.txt
$ head ragoo_output/orderings/NC_024238.1_orderings.txt
41378	-	0.7238458280389666	1.0
```

Any suggestion on how to solve this?
Many thanks,
Pedro

**Comment by malonge** [comment]
Hi Pedro,

I bet the problem is with the fact that the fasta file header is `NC_024238.1 Some species mitochondrion, complete genome` while the gff just has the prefix header `NC_024238.1`. RaGOO should be able to handle this so let me take a look and see what needs to be fixed.

**Comment by mschatz** [comment]
The easy thing to do would be to rewrite the fasta file to avoid spaces.
For example this will convert spaces to underscores:

sed 's/ /_/g' orig.fa > reformat.fa

Good luck!

Mike

**Comment by malonge** [comment]
Ok sorry I actually see what the problem is. You are trying to lift over from the reference to the ragoo pseudomolecules, but this is not supported. The lift-over feature only can lift over features from the contigs to the ragoo pseudomolecules.

For example, lets say you have `contigs.fasta` and an associated set of gene models `contigs.genes.gff`. Then you could lift-over this gff file to `ragoo.fasta`, since it's just and ordered and oriented version of `contigs.fasta`.

There are tools that will lift-over between individuals like what you want to do, but it is a much harder problem. In fact, I think [paftools](https://github.com/lh3/minimap2/tree/master/misc) has such a feature.

**Comment by Asutu** [comment]
OK, that makes sense then, and thank you for suggesting other tools for this. I'm going to close this issue as it's not related with a RaGOO feature.
