### ISSUE TITLE
How to use the short PE reads in the -R parameter

### ISSUE THREAD

**Issue by ShuaishuaiTai** [malonge/RaGOO#70]
Hi Malonge. When we used the short reads for the misassembly correction, the short reads usually have two files: *_1.fq.gz and _2.fq.gz (PE sequencing), but the –R parameter only support one file in your manual (_**As of today, only one file is allowed, so please concatenate your data into one file if necessary**_). How to use the short PE reads in the -R parameter?

**Comment by malonge** [comment]
Hi there,

Paired-end info is not used to detect misassemblies - only coverage. So you can go ahead and just throw those reads into one large file. [RagTag](https://github.com/malonge/RagTag) does allow one to specify a list of files that makes it a little more convenient.

There is a chance that I will revisit this in the future and try to use paired-end info to detect subassemblies.

Thanks
