### ISSUE TITLE
Some question about long sequence

### ISSUE THREAD

**Issue by Zea1nfO** [malonge/RaGOO#72]
Hi sir
   i got a genome contig sequence which is about 2.2~2.3Gb and a reference sequence about 2.1Gb
   When i wanna use ragoo to construct pseudomolecule, i just found that the minimap2 don`t work well.
   i think it may be the result from the "Minimap2 does not work with a single query or database sequence ~2 billion bases or longer (2,147,483,647 to be exact)"
   i read the ragoo paper before, i found you guys can use it on the human genome. So i think you guys must have way to resolve this problem  : )
   i am looking forward for your reply.
   thanks a lot!

**Comment by malonge** [comment]
Hi there,

Thanks for reaching out. This Minimap2 limitation only occurs when a single sequence is about 2G long. Though the human genome is longer than that in total, no single sequence should be that long. In your data, is there a single sequence that long?

If not, perhaps if you describe what looks off about the alignments we can try to debug.

Also, if you are not too invested in RaGOO yet, I highly recommend switching to RaGOO's successor, RagTag:

https://github.com/malonge/RagTag

It's the same concept though much improved.

Thanks,
MIke

**Comment by malonge** [comment]
judging from your username, perhaps you work with maize? :)

**Comment by Zea1nfO** [comment]
> Hi there,
> 
> Thanks for reaching out. This Minimap2 limitation only occurs when a single sequence is about 2G long. Though the human genome is longer than that in total, no single sequence should be that long. In your data, is there a single sequence that long?
> 
> If not, perhaps if you describe what looks off about the alignments we can try to debug.
> 
> Also, if you are not too invested in RaGOO yet, I highly recommend switching to RaGOO's successor, RagTag:
> 
> https://github.com/malonge/RagTag
> 
> It's the same concept though much improved.
> 
> Thanks,
> MIke

Thanks for your reply.
there is on single sequence longer than 2Gb in my contig sequence.
The problem is just like this: 
my command is "ragoo.py -t 30 contig.fa ref.fa"
At the beginning, the minimap2 can use all 30 threads.
but after some time, the minimap2 just continue to use one single threads to running.
it does not look like the usual scence when i use minimap2 to align sequence.
So i think it maybe the result from the long sequence. 
Maybe should i wait a quite long time to wait it ?

**Comment by malonge** [comment]
If you are going with RagTag, you may consider just using Nucmer. It will take a long time, but you will eventually get some decent alignments. And you can always increase the seed/cluster size which will provide my specificity and reduce alignment time, at the expense of sensitivity.

I would be happy to look into the minimap2 alignments, though if you have one sequence that long then it may be beyond the scope of ragoo/ragtag to solve.

**Comment by Zea1nfO** [comment]
> If you are going with RagTag, you may consider just using Nucmer. It will take a long time, but you will eventually get some decent alignments. And you can always increase the seed/cluster size which will yield more specificity and reduced alignment time, at the expense of sensitivity.
> 
> I would be happy to look into the minimap2 alignments, though if you have one sequence that long then it may be beyond the scope of ragoo/ragtag to solve.
Yes, i am "maize farmer".  :)
i think you can get my humor, hahahaha
i will try RagTag as you recommand.
Thanks a lot

**Comment by malonge** [comment]
haha great - if you have any questions, go ahead and open up an issue on the ragtag github. I can show you how to use nucmer with custom parameters if it is not clear from the help messages.

the repetitive nature of the maize genome can be tricky for Minimap2, I think. Perhaps there is some parameter tuning that helps, but nucmer may be the way to go.
