### ISSUE TITLE
make_agp.py not corresponding to ragoo.fasta

### ISSUE THREAD

**Issue by jun3234** [malonge/RaGOO#74]
I used `make_agp.py` to generate an agp file.

And this agp file suggestion that Chr length is not equal to ragoo.fasta.

Then, I wrote a python scripts generate the same file with yours agp file.

![image](https://user-images.githubusercontent.com/20549259/89248728-01d34f80-d643-11ea-8a27-02488553076b.png)

  | my_agp.py | make_agp.py |   | ragoo.fasta.fai
-- | -- | -- | -- | --
Chr1 | 35885076 | 35885076 | -245728 | 36130804
Chr2 | 41244837 | 41244837 | -4696 | 41249533
Chr3 | 30511234 | 30511234 | -24397 | 30535631
Chr4 | 34467794 | 34467794 | -20411 | 34488205
Chr5 | 31660369 | 31660369 | -7888 | 31668257
Chr6 | 31174887 | 31174887 | -3256 | 31178143
Chr7 | 26023135 | 26023135 | -52366 | 26075501
Chr8 | 26146728 | 26146728 | -13756 | 26160484
Chr9 | 26952743 | 26952743 | -6817 | 26959560
Chr10 | 25198119 | 25198119 | -4927 | 25203046
Chr11 | 32539074 | 32539074 | -33035 | 32572109
Chr12 | 23847855 | 23847855 | -3339 | 23851194
Chr13 | 24729235 | 24729235 | -209829 | 24939064
Chr14 | 48387154 | 48387154 | -2092 | 48389246
Chr15 | 37080300 | 37080300 | -15334 | 37095634

So, I want to know why this differ between agp file and ragoo.fasta?

**Comment by malonge** [comment]
Hi there,

First of all, I definitely recommend you switch your analysis to [RagTag](https://github.com/malonge/RagTag). It is much improved over RaGOO and I doubt you will see any bugs with the AGP files.

As for RaGOO, could you share the commands used to generate the RaGOO output and the subsequent AGP file?

Thanks

**Comment by jun3234** [comment]
Very thanks!

I will try the RagTag.

I'm sorry about the aforementioned issue. It was my mistake that I regarded the second column as Chr length by mistake. 
The true is the third column.

Part of `agp` file like this:

Chr0_RaGOO | 19527394 | 19606320 | 751 | W | Chr15_b80 | 1 | 78927 | +
-- | -- | -- | -- | -- | -- | -- | -- | --
HML_HiC_scaffold_10_RaGOO | 35885282 | 36130804 | 413 | W | Chr5_b92 | 1 | 245523 | -
HML_HiC_scaffold_11_RaGOO | 41245152 | 41249533 | 631 | W | HiC_scaffold_815_b0 | 1 | 4382 | +
HML_HiC_scaffold_12_RaGOO | 30511390 | 30535631 | 313 | W | Chr10_b1 | 1 | 24242 | -
HML_HiC_scaffold_13_RaGOO | 34468119 | 34488205 | 651 | W | Chr6_b5 | 1 | 20087 | -
HML_HiC_scaffold_14_RaGOO | 31660558 | 31668257 | 379 | W | HiC_scaffold_157_b0 | 1 | 7700 | +
HML_HiC_scaffold_15_RaGOO | 31175096 | 31178143 | 419 | W | Chr10_b0 | 1 | 3048 | +
HML_HiC_scaffold_1_RaGOO | 26023306 | 26075501 | 343 | W | HiC_scaffold_592_b0 | 1 | 52196 | -
HML_HiC_scaffold_2_RaGOO | 26146857 | 26160484 | 259 | W | Chr4_b168 | 1 | 13628 | -
HML_HiC_scaffold_3_RaGOO | 26952889 | 26959560 | 293 | W | HiC_scaffold_180_b0 | 1 | 6672 | +
HML_HiC_scaffold_4_RaGOO | 25198310 | 25203046 | 383 | W | HiC_scaffold_473_b0 | 1 | 4737 | -
HML_HiC_scaffold_5_RaGOO | 32539274 | 32572109 | 401 | W | Chr13_b26 | 1 | 32836 | -
HML_HiC_scaffold_6_RaGOO | 23847977 | 23851194 | 245 | W | HiC_scaffold_885_b0 | 1 | 3218 | +
HML_HiC_scaffold_7_RaGOO | 24729325 | 24939064 | 181 | W | Chr12_b60 | 1 | 209740 | +
HML_HiC_scaffold_8_RaGOO | 48387377 | 48389246 | 447 | W | HiC_scaffold_844_b0 | 1 | 1870 | +
HML_HiC_scaffold_9_RaGOO | 37080466 | 37095634 | 333 | W | Chr3_b0 | 1 | 15169 | -

**Comment by malonge** [comment]
No problem. Is there still an issue that you are observing? If you are referring to the AGP file, the second and third column actually refer to the coordinates of that component in that object. You can check out the specs [here](https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/).

**Comment by jun3234** [comment]
Yes, thanks. 
Now, all is fine.
