### ISSUE TITLE
PLASMIDS

### ISSUE THREAD

**Issue by jotes35** [malonge/RaGOO#75]
Hi RaGOO team, in your document you made mention that Any unlocalized contigs are concatenated and placed in "Chr0_RaGOO". I am working with M. ulcerans and the complete circular sequence and its plasmids are stored in different files.  So if I use lets say the chromosomal reference sequence for the guided assembly, does it mean that contigs which do not match the reference (and possibly are plasmids) will placed in the Chro_RaGOO?  and therefore if I am looking for the plasmids thats the file to look for ?

**Comment by malonge** [comment]
Hi there,

Firstly, I recommend using [RagTag](https://github.com/malonge/RagTag) instead of RaGOO if at all possible. It is superior in many ways. The following applies to both RaGOO and RagTag.

I think what you said sounds good. Of course, you always run the risk of the plasmid sequence being placed into chromosomes due to repetitive mappings. If you can identify the plasmid contigs beforehand, you can ask for them to be left unplaced by using the `-j` parameter.

Thanks

**Comment by jotes35** [comment]
Hi @malonge,

I blasted some of the contigs and they come out as 100% identity with a plasmid. So I guess from your explanation I will have to use the -j parameter. I will update you on the outcome once I implement the pipeline. Thanks

**Comment by malonge** [comment]
I guess it depends. If a contig maps with 100% identity with equal coverage to two different positions, it is completely ambiguous so it probably shouldn't be placed anywhere. But if it covers one region better than another then that might be sufficient to discriminate between plasmid and chromosome sequence, so you could let ragoo/ragtag take a shot a placing it.

**Comment by jotes35** [comment]
One last thing,

Does Ragtag do stitching (remove Ns). I did not find that in the document.   ( I will also like to generate a circularized result)

**Comment by malonge** [comment]
Hi there,

I am not sure what you are referring to. Are you asking about filling gaps between adjacent contigs? I can say that both RaGOO and RagTag strictly order and orient input sequences - they don't add (except for "N"s) or subtract or change any sequence.

**Comment by jotes35** [comment]
Yes. I mean filling of gaps

**Comment by malonge** [comment]
Ok yeah unfortunately these tools don't perform gap filling. Let me know if you have any other questions.
