### ISSUE TITLE
New sequence header

### ISSUE THREAD

**Issue by jotes35** [malonge/RaGOO#77]
Hi @Malong, after using the scaffold command for rag tag I realized a new sequence header has been introduced to the new scaffold. My draft assembly is M. ulcerans and the reference genome I used is Agy99. After I found out that the two new headers were introduced.
1. BX649209.1  (This is the plasmid of Agy99)
2. CP000325.1  (This is the complete genome).

Those two headers were present in the reference genome I used. Does it mean that ragtag identified some contigs as exact match to these two headers in the genome and therefore they were renamed to match the two headers in the reference genome?

**Comment by malonge** [comment]
RagTag uses the reference headers as a base and then adds `_RagTag` to distinguish the scaffold from the original reference sequence. That means that, for example, `CP000325.1` was used to scaffold the contigs that makeup `CP000325.1_RagTag` (so `CP000325.1` and `CP000325.1_RagTag` are syntenic).Do you see the `_RagTag` suffix? If there are any reference sequences you don't want to use as the basis for scaffolding, you can specify their headers with `-e`.

**Comment by jotes35** [comment]
Yes. I saw the _RagTag.  I think this has given me another idea for identifying my other sequences. I am looking for insertional sequence and plasmids as well.  So my strategy will be to lump up their respective reference genomes into a single file and let ragtag do the reordering and identifying. This will be alternative to blasting all the contigs which will take time. 

Thanks for the information @malonge

**Comment by malonge** [comment]
great - let me know if I can help out with anything else.

**Comment by jotes35** [comment]
Thanks. In the same draft genome i had these two contigs lets 10 and 11. These two contgs all gave me the same blast hit which is the plasmid  BX649209.1  .
But ragtag only reported on of them in the confidence file. So does it mean that ragtag takes the sequence that best matches the reference genome? or there are other criteria for choosing? 
In my blast output the percentage identity of contig 10 was higher than contig 11 but ragtag chose contig 11

**Comment by malonge** [comment]
Hi there, 

RagTag does not try to pick the "best" in any way. Rather, any contig that meets certain criteria will be placed, even if they are redundant. I suggest you look at the alignments in `query_against_ref.paf` and see how those sequences align. You can also. run ragtag with `--debug` to get the filtered and merged alignments. You will want to see `ragtag.scaffolds.debug.merged.paf` for the alignments that RagTag actually uses for scaffolding.

**Comment by jotes35** [comment]
Hi Malonge, thanks for the information. I was able to extract both plasmid and chromosome from my contigs. But I wanted to know if combining my two reference sequences into a single fasta file was appropriate or I have to do seperate runs for reference plasmid and reference chromosome.

**Comment by malonge** [comment]
Hi there,

Please correct me if I am misunderstandig, but there should generally be a 1-to-1 relationship between the query and the reference. Of course there can be large differences between the two assemblies, but they should each represent the same abstract genome (e.g. query and ref both make up a nuclear genome or query and. ref both make up one linear and one plasmid genome)

**Comment by jotes35** [comment]
Hi @malong,

my sample sequencing protocol was designed such that both plasmid and genome sequence were captured in the same file. eg. Sample1 will contain both plasmid and circular genome (M. ulcerans). So I thought maybe when I combine the reference for both the genome and the plasmid ragtag will be a best strategy. In the end the ragtag.scaffold.fasta showed both referenceids_RagTag. i.e >BX649209.1_RagTag  and CP000325.1_RagTag. So I concluded that both plasmids and genome were identified.

**Comment by malonge** [comment]
Yeah I agree with your strategy - I think that should work

Thanks,
Mike

**Comment by jotes35** [comment]
Thanks malonge.

I have another sample which is Salmonella typhi genomes and I used ragtag to generate scaffolds. I combined the reference genome of 6 different strains to a single file. Based on my earlier tests I was expecting that only one of them will be a hit but interestingly some or all of the references were used by ragtag to generate scaffolds in all the samples. Does it mean my sample contained different strains? I would be happy if we could discuss this output and I make my final decision.  The references I used were AL513382.1,NC_003197.2, NZ_CP012598.1, NZ_CP016408.1, NZ_CP018657.1, NZ_CP025453.1. Below are the contents of ragtag.scaffolds.fasta for each sample  

Sample 2
>AL513382.1_RagTag


Sample 1
>AL513382.1_RagTag
>NC_003197.2_RagTag
>NZ_CP012598.1_RagTag
>NZ_CP016408.1_RagTag
>NZ_CP018657.1_RagTag
>NZ_CP025453.1_RagTag

Sample 2
>AL513382.1_RagTag
>NZ_CP012598.1_RagTag
>NZ_CP016408.1_RagTag
>NZ_CP025453.1_RagTag

Sample 3
>AL513382.1_RagTag
>NZ_CP012598.1_RagTag
>NZ_CP016408.1_RagTag
>NZ_CP025453.1_RagTag

Sample 4
>AL513382.1_RagTag
>NC_003197.2_RagTag
>NZ_CP012598.1_RagTag
>NZ_CP016408.1_RagTag
>NZ_CP025453.1_RagTag

Sample  5
>AL513382.1_RagTag
>NZ_CP012598.1_RagTag
>NZ_CP016408.1_RagTag
>NZ_CP025453.1_RagTag

**Comment by malonge** [comment]
Hi there,

Generally speaking, if a query sequence is assigned to a particular reference sequence then that means that there was strong evidence for that in the minimap2 alignments. I recommend running ragtag with `--debug` and looking at the "merged" debugging paf file. If you see any unexpected hits to different references, it might be best at that point to BLAST those sequences or something along those lines. I must admit I have no expertise in bacterial genome classification but hopefully, the debugging info can lead you in the right direction.
