### ISSUE TITLE
Requiring specific mapping segment lengths

### ISSUE THREAD

**Issue by selasphoruskershaw** [malonge/RaGOO#79]
Hi @malonge ,

I am wondering if there is a way to require a minimum mapping segment length of 10kb for scaffolds shorter than 1 Mbp, and to require a mapping segment length of at least 50kb for scaffolds longer than 1 Mbp.

Also, is there a way I can ensure that half of the alignment segments per scaffold align to the same chromosomes (I know that I can interpret the confidence score to enforce the requirement that more than half of the total scaffold length aligns to the same chromosome).

Thanks for your help!

**Comment by selasphoruskershaw** [comment]
Also, is there a way to import a mashmap outfile and use that instead of what minimap2 produces? I would like to compare the results of each if possible. Thank you!

**Comment by malonge** [comment]
Hi there,

Would you be able to use [RagTag](https://github.com/malonge/RagTag) instead? If so, you can open up an issue there and I will help you out. Or else we can use RaGOO, though this is more difficult to do with RaGOO.

Thanks,
Mike

**Comment by selasphoruskershaw** [comment]
Definitely, I will post this issue on RagTag and install in the meantime. Looking forward to your response, thanks!

**Comment by malonge** [comment]
thank you!
