### ISSUE TITLE
Grouping confidence scores definition

### ISSUE THREAD

**Issue by Asutu** [malonge/RaGOO#8]
Hi,

I'm trying to determine a reasonable grouping confidence score for the placement of scaffolds. The default seems to work OK (`-i 0.2`), but I'd also like to try with other values. In the preprint you have a section defining the confidence scores (clustering, location and orientation), but on the program `-i` is actually defined as `grouping confidence score`. Is this the same as clustering? And could a `-i 0.2` be said that the scaffold is covered ~20% of its length in its assigned reference chromosome?

Many thanks,
Pedro

**Comment by malonge** [comment]
Hi Pedro,

Yes, sometimes I have used the two terms interchangeably, but I should pick one. Grouping confidence score = clustering confidence score. 

It is defined as the total number of bp that a contig covers on its assigned chromosome divided by the total number of bp it covers in the entire reference. 

So if a contig covers 100 bp on chromosome 1, and it covers 20 bp on chromosomes 2 and 3, it would be assigned to chromosome 1 and the score would be 100/140.

**Comment by Asutu** [comment]
Perfect, this was really helpful.
Many thanks.

**Comment by malonge** [comment]
You're welcome
