### ISSUE TITLE
How to understad output ?

### ISSUE THREAD

**Issue by YuChrming** [malonge/RaGOO#82]
Dear author,
I ran the ragoo pipline and got a goodish result.But I not really understand the result files, `orders/orderings.txt`, and `groups/contigs.txt` meaning.
orderings.txt:
```
ptg000244l      -       0.0014127063882183142   0.6813073651220058
ptg000014l      -       0.05063969092827449     0.8835199739787316
ptg001305l      -       0.0021915977376244337   0.38366066557555917
ptg001332l      -       0.0021915977376244337   0.38366066557555917
ptg000004l      -       0.6282196481391924      0.934203313107705
```
What those numbers mean?Are they start and end positions?

orderings.txt:
```
ptg000004l      0.7479725314109346
ptg000014l      0.31663738688109305
ptg000244l      0.20284798017528835
ptg001305l      0.31718519802409223
ptg001332l      0.34471391570520366
```
What the numbers mean?

And, if I want to know what the place a contig is in the ragoo.fasta ,what should Ido ?

Really thanks !!

**Comment by malonge** [comment]
RaGOO is no longer supported. Please use [RagTag](https://github.com/malonge/RagTag) and open an issue there if you still have questions.
